### ISSUE TITLE
pip installation failure: "NotImplementedError: Can't perform this operation for loaders without 'get_data()" 

### ISSUE THREAD

**Issue by jszym** [escherba/python-metrohash#2]
PIP installation seems to fail on Windows under both Python 2.7 and Python 3.5 with a weird "NotImplementedError: Can't perform this operation for loaders without 'get_data()" error.

Anybody know how to resolve this?

```
> pip install metrohash
Collecting metrohash
  Using cached metrohash-0.0.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\[REDACTED]\AppData\Local\Temp\pip-build-vxips9m8\metrohash\setup.py", line 104, in <module>
        long_description=resource_string(__name__, 'README.rst'),
      File "C:\[REDACTED]\env\lib\site-packages\pkg_resources\__init__.py", line 1173, in resource_string
        self, resource_name
      File "C:\[REDACTED]\env\lib\site-packages\pkg_resources\__init__.py", line 1605, in get_resource_string
        return self._get(self._fn(self.module_path, resource_name))
      File "C:\[REDACTED]\env\lib\site-packages\pkg_resources\__init__.py", line 1685, in _get
        "Can't perform this operation for loaders without 'get_data()'"
    NotImplementedError: Can't perform this operation for loaders without 'get_data()'

    ----------------------------------------
```

**Comment by mbarkhau** [comment]
I get this for Python 3.6 on Ubuntu also.

**Comment by Dobatymo** [comment]
I also get this error for all 3.x version I tested (3.5, 3.6, 3.7 on Windows and 3.6 on Ubuntu).

**Comment by TACIXAT** [comment]
This error persists. Maybe archive the project if it only works on Python 2x?

**Comment by escherba** [comment]
The package now works with Python 3.6-3.10 and all three major platforms (Windows, Mac, Linux). Currently only verified on x86-64, will check M1 support shortly.

**Comment by CatMitch** [comment]
I still get this problem on python 3.7

**Comment by escherba** [comment]
@CatMitch Very strange. Do you mind posting more info? (CPU, OS version)?

I just tried the following and was unable to reproduce:

```bash
$ conda create -y -c conda-forge -n py37 python=3.7 numpy
$ conda activate py37
(py37) $ pip install metrohash
Collecting metrohash
  Downloading metrohash-0.3.0.post0-cp37-cp37m-macosx_10_9_x86_64.whl (36 kB)
Installing collected packages: metrohash
Successfully installed metrohash-0.3.0.post0
(py37) $ python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:59:23)
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```
```python
>>> import metrohash
>>> dir(metrohash)
['MetroHash128', 'MetroHash64', '__all__', '__author__', '__builtins__', '__doc__', '__email__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__test__', '__version__', 'hash128', 'hash128_hex', 'hash128_int', 'hash64', 'hash64_hex', 'hash64_int']
>>> from metrohash import hash64
>>> hash64("abc")
b'\xbb\xff\xfa\xe6$UO\xed'
```

**Comment by escherba** [comment]
@CatMitch it might be that your Pip is using old cached version. For example, line 104 below (the one where the error was originally occuring) no longer exists in the current codebase:

```
      File "...\metrohash\setup.py", line 104, in <module>
        long_description=resource_string(__name__, 'README.rst'),
```
So it would also be helpful to see a copy of your exact error message even if it might be similar to the one at the top of this thread.

**Comment by CatMitch** [comment]
Ok, mine worked in the end I think it was just looking in the wronog place. My __name__ had to be changed to the package name and it worked fine
